### ISSUE TITLE
CV with an image

### ISSUE THREAD

**Issue by anderflash** [jaspervdj/jaspervdj#10]
Hi,

Could you please try to put an image within the CV markdown?

When I put an image to a markdown file which will be XeTeX'ed, it gives an error:
```bash
  updated posts/2012-08-12-spqr.markdown (pdf)
  updated posts/2012-10-07-rosa-rosa-rosam.markdown (pdf)
  updated posts/2012-11-28-carpe-diem.markdown (pdf)
  updated posts/2012-12-07-tu-quoque.markdown (pdf)
  updated posts/2013-08-14-topdf.markdown (pdf)
_cache/tmp/86fbf2c8e3218a180a34e1d7be46129d-xelatex.pdf: renameFile: does not exist (No such file or directory)
```
It compiles the 4 pdfs (`spqr`, `rosa`, `carpe` and `quoque`), but not for `topdf`.
What do you think?
Thanks.

**Comment by jaspervdj** [comment]
Closing as I'm not sure what this refers to.
