### ISSUE TITLE
invalid SSL cert

### ISSUE THREAD

**Issue by seutje** [jaspervdj/jaspervdj#14]
Most browsers will trigger the "OMG insecure!" warning.

**Comment by jaspervdj** [comment]
Yes, I am aware of the problem but unfortunately I'm on holiday in a fairly remote place so I cannot fix the problem right now.  Thanks for reminding me though!

**Comment by jaspervdj** [comment]
Thanks for the heads up, fixed now.  I also put this in my `crontab` now but should really look at migrating the server.
