### ISSUE TITLE
[ERROR] dot: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by luckypoem** [jaspervdj/jaspervdj#15]
hi.

root@AR:/usr/local/jaspervdj-site# stack init
root@AR:/usr/local/jaspervdj-site# stack build

it exports:
...
Linking .stack-work/dist/i386-linux/Cabal-1.22.5.0/build/jaspervdj/jaspervdj 
jaspervdj-0.1.0.0: copy/register
Installing executable(s) in
/usr/local/jaspervdj-site/.stack-work/install/i386-linux/lts-6.24/7.10.3/bin
root@AR:/usr/local/jaspervdj-site# .stack-work/dist/i386-linux/Cabal-1.22.5.0/build/jaspervdj/jaspervdj build

it exports:
...
[ERROR] dot: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
root@AR:/usr/local/jaspervdj-site# 

how to fix it?
TKS.

**Comment by jaspervdj** [comment]
You need `dot` installed.  It is part of the graphviz suite.

**Comment by luckypoem** [comment]
hi.

i installed dot,still "[ERROR] dot: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)" appears:

root@AR:/usr/local/jaspervdj-site# .cabal-sandbox/bin/jaspervdj rebuild
it exports:
...
[ERROR] dot: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
root@AR:/usr/local/jaspervdj-site# root@AR:/usr/local/jaspervdj-site# 

how to fix it?
TKS.

**Comment by luckypoem** [comment]
i see.
previously i ran "cabal install dot",it didn't fix the error.
now i ran "apt-get install graphviz -y",it fixed the error.

**Comment by SimonBaars** [comment]
Graphviz needs to be present on the system, which it wasn't for me. Installing graphviz fixed the problem.
