### ISSUE TITLE
Your flip article

### ISSUE THREAD

**Issue by danwdart** [jaspervdj/jaspervdj#19]
Hey, I read your flip article and thought it was really good.

You commented that one could make their own combinators to flip longer lists of arguments around, and I wanted to tell you that the composition-extra package has done just this. See:

https://hackage.haskell.org/package/composition-extra-2.0.0/docs/Data-Function-Apply.html#v:-45--45--36-
https://hackage.haskell.org/package/composition-extra-2.0.0/docs/Data-Function-Slip.html#v:-60--126--62--62- 

Maybe you'd like to include this.

Thanks!

**Comment by jaspervdj** [comment]
Hi Dan, thanks for the pointer, I wasn't aware of this package!  I've added the link in https://github.com/jaspervdj/jaspervdj/commit/e7dbc58af379113f97c4ae07695ae723ee50b482.
